version: '3.1'
services:

  mongo:
    image: mongo:4.4
    restart: on-failure
    container_name: mongo-demo
    volumes:
      - ./init-mongo-db.js:/docker-entrypoint-initdb.d/init-mongo-db.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=demo-db
    networks:
      - demo_net
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    networks:
      - demo_net
networks:
  demo_net:
